name: "Docs"
description: "Tarea de documentación"
title: "[Docs] <título conciso>"
labels: ["docs", "sprint-1"]
assignees: []
body:
  - type: textarea
    id: alcance
    attributes:
      label: Alcance
      description: ¿Qué documento(s) se crean/actualizan?
      placeholder: docs/...
    validations:
      required: true
  - type: textarea
    id: contenido
    attributes:
      label: Contenido propuesto
      description: Breve bosquejo o checkpoints.
    validations:
      required: true
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: PR incluirá "Closes #<n>"
        - label: Revisión de claridad/consistencia

