name: Auto-close issues on "resolved"

on:
  issue_comment:
    types: [created, edited]

permissions:
  issues: write
  contents: read

jobs:
  close-on-resolved:
    if: github.event.issue.pull_request == null
    runs-on: ubuntu-latest
    steps:
      - name: Close issue when comment contains resolved/resuelto
        uses: actions/github-script@v7
        with:
          script: |
            const body = context.payload.comment?.body || "";
            const isOpen = context.payload.issue?.state === "open";
            if (!isOpen) { core.info("Issue not open"); return; }
            const regex = /\b(resolved|resuelto|resuelta)\b/i;
            if (!regex.test(body)) { core.info("No keyword found"); return; }
            const commenter = context.payload.comment.user.login;
            const author = context.payload.issue.user.login;
            let allowed = false;
            if (commenter === author) {
              allowed = true;
            } else {
              try {
                await github.rest.repos.checkCollaborator({ owner: context.repo.owner, repo: context.repo.repo, username: commenter });
                allowed = true;
              } catch {}
            }
            if (!allowed) { core.info(`Commenter ${commenter} not authorized`); return; }
            const labels = (context.payload.issue.labels || []).map(l => typeof l === 'string' ? l : l.name);
            if (labels.includes('needs-verification')) {
              await github.rest.issues.removeLabel({ owner: context.repo.owner, repo: context.repo.repo, issue_number: context.payload.issue.number, name: 'needs-verification' }).catch(() => {});
            }
            await github.rest.issues.update({ owner: context.repo.owner, repo: context.repo.repo, issue_number: context.payload.issue.number, state: 'closed' });
            await github.rest.issues.createComment({ owner: context.repo.owner, repo: context.repo.repo, issue_number: context.payload.issue.number, body: "Cerrado automáticamente tras comentario 'resolved/resuelto'. Si fue un error, vuelva a abrir el issue." });

